[package]
name = "std-dl"
version = "0.1.0"
authors = ["Adel Prokurov <adel.prokurov@protonmail.com>"]
edition = "2018"

[dependencies]
jazzvm = {path = "../jazz-vm"}

[lib]
crate-type = ["cdylib","rlib"]