[package]
name = "jazz"
version = "0.1.0"
authors = ["playx"]
edition = "2018"

[dependencies]
hmap = "0.1.0"
fxhash = "0.2.1"
rand = "0.6.5"
walkdir = "2.2.7"
crossterm_terminal = "0.1.0"
waffle = {git = "https://github.com/jazz-lang/waffle"}
hashbrown = "0.1.8"
gc = "0.3.2"
time = "0.1.42"