[package]
name = "jazzc"
version = "0.1.0"
authors = ["Adel Prokurov <adel.prokurov@protonmail.com>"]
edition = "2018"

[dependencies]
hmap = "0.1"
structopt = "0.2"
time = "0.1.42"
hashlink = "0.3"
byteorder = "1.3.2"
libc = "0.2"
wrc = "0.4"
parking_lot = "0.9"
lazy_static = "1.3"
rayon = "1.1"
[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }
kernel32-sys = "0.2"
[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'
