[package]
name = "jazzc"
version = "0.1.0"
authors = ["Adel Prokurov <adel.prokurov@protonmail.com>"]
edition = "2018"

[dependencies]
hmap = "0.1"
nabox = {path = "nabox"}
structopt = "0.2"
time = "0.1.42"
linked-hash-map = "0.5"
byteorder = "1.3.2"
libc = "0.2"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
panic = 'abort'