[package]
name = "jazzlight"
version = "0.1.0"
authors = ["Adel Prokurov <adel.prokurov@protonmail.com>"]
edition = "2018"

[dependencies]
time = "0.1"
parking_lot = "0.9"
lazy_static = "1.4"
rand = "0.7"
mimalloc = "0.1"
hashlink = "0.3"
byteorder = "1.3"