[package]
name = "jazzvm"
version = "0.1.0"
authors = ["Adel Prokurov <adel.prokurov@protonmail.com>"]
edition = "2018"

[profile.release]
panic = "abort"
[dependencies]
gc = {path = "../gc-rs/gc"}
gc_derive = "0.3.2"
fnv = "1.0.6"